language: python
python:
  - "2.7"
# command to install dependencies
before_install:
  - "pip install -q cython"
  - "pip install -q numpy"
  - "pip install -q pytram"
install:
  - "python setup.py develop"
# command to run tests
script: nosetests
